# Imagem base com suporte nativo a ARM64 (Mac) e AMD64 (Nuvem)
FROM python:3.12-slim

WORKDIR /code

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]