
services:
  # 1. O Garçom (Leve e rápido)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - banco_dados

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - banco_dados

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  banco_dados:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contradito
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: